# Generated by Django 5.0.6 on 2024-05-22 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clocks', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
