# Generated by Django 5.0.6 on 2024-05-22 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clocks', '0002_delete_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='category',
        ),
        migrations.DeleteModel(
            name='CategoryWatch',
        ),
    ]
